version: "3.2"
services:

  mongo:
    image: mongo:4
    networks:
      - internal
    restart: always

  flower-node:
    build:
      context: .
      dockerfile: Dockerfile-node
    image: flower-node:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - internal
    command: "yarn start"
    environment:
      REACT_APP_FLOWER_SERVER_IP: mongo
      REACT_APP_FLAG_REGEX: "FLG[0-9a-f]{29}"
      SERVICES_ADDRESS: 127.0.0.1

  flower-python:
    build:
      context: .
      dockerfile: Dockerfile-python
    image: flower-python:latest
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - internal
    volumes:
      - ./shared:/shared
    environment:
      REACT_APP_FLOWER_SERVER_IP: mongo
      REACT_APP_FLAG_REGEX: "FLG[0-9a-f]{29}"

networks:
  internal:
