version: "3.2"
services:
  mongo:
    image: mongo:5
    networks:
      - internal
    restart: always
    ports:
      - "127.0.0.1:27017:27017"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile-frontend
    image: tulip-frontend:latest
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - mongo
    networks:
      - internal
    environment:
      FLAG_REGEX: "SAAR\\{[A-Za-z0-9-_]{32}\\}"
      TULIP_MONGO: mongo:27017
      REACT_APP_FLOWER_SERVICES: 127.0.0.1

  api:
    build:
      context: .
      dockerfile: Dockerfile-python
    image: tulip-api:latest
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - mongo
    networks:
      - internal
    volumes:
      - ./shared:/shared
    environment:
      TULIP_MONGO: mongo:27017
      FLAG_REGEX: "SAAR\\{[A-Za-z0-9-_]{32}\\}"

  assembler:
    build:
      context: services/go-importer
      dockerfile: Dockerfile-assembler
    image: tulip-assembler:latest
    depends_on:
      - mongo
    networks:
      - internal
    volumes:
      - /ssd/ICC_DUMP/SAAR/nflog:/traffic:ro
    command: "./assembler -dir /traffic"
    environment:
      TULIP_MONGO: mongo:27017
      FLAG_REGEX: "SAAR\\{[A-Za-z0-9-_]{32}\\}"

  enricher:
    build:
      context: services/go-importer
      dockerfile: Dockerfile-enricher
    image: tulip-enricher:latest
    depends_on:
      - mongo
    networks:
      - internal
    volumes:
      - /ssd/ICC_DUMP/SAAR/nflog:/traffic:ro
    command: "./enricher -eve /traffic/eve.json"
    environment:
      TULIP_MONGO: mongo:27017

networks:
  internal:
