version: "3.2"
services:
  mongo:
    image: mongo:5
    networks:
      - internal
    restart: always
    ports:
      - "27017:27017"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile-frontend
    image: flower-frontend:latest
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - internal
    environment:
      REACT_APP_FLAG_REGEX: "SAAR\\{[A-Za-z0-9-_]{32}\\}"
      REACT_APP_FLOWER_SERVICES: 127.0.0.1

  api:
    build:
      context: .
      dockerfile: Dockerfile-python
    image: flower-python:latest
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - internal
    volumes:
      - ./shared:/shared
    environment:
      REACT_APP_FLOWER_MONGO: mongo
      REACT_APP_FLAG_REGEX: "SAAR\\{[A-Za-z0-9-_]{32}\\}"

  assembler:
    build:
      context: services/go-importer
      dockerfile: Dockerfile-assembler
    image: assembler:latest
    depends_on:
      - mongo
    networks:
      - internal
    volumes:
      - /traffic:/traffic:ro
    command: "./assembler -dir /traffic"
    environment:
      REACT_APP_FLOWER_MONGO: mongo
      REACT_APP_FLAG_REGEX: "SAAR\\{[A-Za-z0-9-_]{32}\\}"

  enricher:
    build:
      context: services/go-importer
      dockerfile: Dockerfile-enricher
    image: enricher:latest
    depends_on:
      - mongo
    networks:
      - internal
    volumes:
      - /traffic:/traffic:ro
    command: "./go-importer -eve /traffic/eve.json"
    environment:
      REACT_APP_FLOWER_MONGO: mongo
      REACT_APP_FLAG_REGEX: "SAAR\\{[A-Za-z0-9-_]{32}\\}"

networks:
  internal:
