version: "3.2"
services:
  mongo:
    image: mongo:5
    networks:
      - internal
    restart: always
    # TODO; REMOVE; super hecking insecure
    # Just for dev purposes
    ports:
      - "27017:27017"

  flower-frontend:
    build:
      context: frontend
      dockerfile: Dockerfile-frontend
    image: flower-frontend:latest
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - internal
    environment:
      REACT_APP_FLOWER_MONGO: mongo
      REACT_APP_FLAG_REGEX: "FLG[0-9a-f]{29}"
      REACT_APP_FLOWER_SERVICES: 127.0.0.1

  flower-node:
    build:
      context: .
      dockerfile: Dockerfile-node
    image: flower-node:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - internal
    command: "yarn start"
    environment:
      REACT_APP_FLOWER_MONGO: mongo
      REACT_APP_FLAG_REGEX: "FLG[0-9a-f]{29}"
      REACT_APP_FLOWER_SERVICES: 127.0.0.1

  flower-python:
    build:
      context: .
      dockerfile: Dockerfile-python
    image: flower-python:latest
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - internal
    volumes:
      - ./shared:/shared
    environment:
      REACT_APP_FLOWER_MONGO: mongo
      REACT_APP_FLAG_REGEX: "FLG[0-9a-f]{29}"

  flower-importer:
    build:
      context: .
      dockerfile: Dockerfile-golang
    image: flower-importer:latest
    depends_on:
      - mongo
    networks:
      - internal
    volumes:
      - ./shared:/shared
    environment:
      REACT_APP_FLOWER_MONGO: mongo
      REACT_APP_FLAG_REGEX: "FLG[0-9a-f]{29}"

networks:
  internal:
