version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/python:3.8 
    steps:
      - checkout 
      - setup_remote_docker
      - run: echo "Running docker compose up!"
      - run: docker-compose up -d
      - run: python services/tests.py

